AWSTemplateFormatVersion: "2010-09-09"
Description: "DBCS A2 - Step 5 Secure S3 Bucket with Encryption and Public Access Block"

Resources:
  SecureAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: dbcs-a2-secure-bucket

Outputs:
  BucketName:
    Description: "Encrypted S3 bucket for application data"
    Value: !Ref SecureAppBucket